name: chatbot
channels:
  - defaults
dependencies:
  - pandas=1.2.4
  - gspread=4.4.0
  - oauth2client=4.1.3
  - google-auth-oauthlib=0.4.4
  - google-auth=1.30.1
  - smtplib
  - requests
  - beautifulsoup4
