name: Python Package using Anaconda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      run: |
        wget -qO- https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > ~/miniconda.sh
        bash ~/miniconda.sh -b -p $HOME/miniconda
        source ~/miniconda/etc/profile.d/conda.sh
        conda activate base
        conda env update -n chatbot --file environment.yml
        conda activate chatbot

    - name: Install dependencies
      run: |
        conda install -c conda-forge pandas

    - name: Run Python script
      run: |
        python StockTracker.py
