name: Python Package using Anaconda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.9'

    - name: Create conda environment
      run: conda env create -n chatbot -f environment.yml

    - name: Activate conda environment
      run: conda activate chatbot

    - name: Run Python script
      run: python StockTracker.py
