name: Python Package using Anaconda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      run: |
        wget -qO- https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > ~/miniconda.sh
        bash ~/miniconda.sh -b -p $HOME/miniconda
        echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
        source ~/.bashrc
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda env create --file environment.yml

    - name: Run Python script
      run: |
        conda activate chatbot
        python StockTracker.py
