name: chatbot
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas
  - gspread
  - oauth2client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        conda env create -n chatbot
        conda activate chatbot
        conda env update -n chatbot --file environment.yml
    - name: Run StockTracker.py
      run: python StockTracker.py

